// optin-asset.mjs — opts all five project accounts into the payment asset.
//
// On Algorand an account cannot receive an ASA it has not opted into. An
// opt-in is a zero-amount asset transfer from an account to itself. It costs
// ~0.001 ALGO in fees and raises the account's minimum balance by 0.1 ALGO.
//
// No faucet needed. Opting in does not require holding any of the asset.
//
// Run from the project root:  node scripts/optin-asset.mjs

import algosdk from 'algosdk';
import fs from 'node:fs';
import path from 'node:path';

const ALGOD_SERVER = 'https://testnet-api.algonode.cloud';
const ALGOD_PORT = 443;

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const DIM = '\x1b[2m';
const RESET = '\x1b[0m';

const bar = () => console.log('='.repeat(72));

// ---------------------------------------------------------------------------
// Read the asset id from .env
// ---------------------------------------------------------------------------
const envPath = path.join(process.cwd(), '.env');

if (!fs.existsSync(envPath)) {
  console.log('ERROR: .env not found. Run this from the project root.');
  process.exit(1);
}

let assetId = null;
let assetSymbol = 'ASSET';

for (const raw of fs.readFileSync(envPath, 'utf8').split('\n')) {
  const line = raw.trim();
  if (line.startsWith('PAYMENT_ASSET_ID=')) assetId = line.slice(17).trim();
  if (line.startsWith('PAYMENT_ASSET_SYMBOL=')) assetSymbol = line.slice(21).trim();
}

if (!assetId) {
  console.log('ERROR: PAYMENT_ASSET_ID not found in .env');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Read accounts and their secret keys from the probe folder
// ---------------------------------------------------------------------------
const home = process.env.USERPROFILE ?? process.env.HOME ?? '';
const accountsPath = path.join(home, 'x402-probe', 'testnet-accounts.env');

if (!fs.existsSync(accountsPath)) {
  console.log('ERROR: could not find ' + accountsPath);
  console.log('This script needs the secret keys generated by gen-accounts.mjs.');
  process.exit(1);
}

const accounts = {};

for (const raw of fs.readFileSync(accountsPath, 'utf8').split('\n')) {
  const line = raw.trim();
  const eq = line.indexOf('=');
  if (eq === -1) continue;

  const key = line.slice(0, eq);
  const value = line.slice(eq + 1).trim();

  if (key.endsWith('_ADDRESS')) {
    const role = key.replace('_ADDRESS', '');
    accounts[role] = { ...(accounts[role] ?? {}), address: value };
  } else if (key.endsWith('_SK_B64')) {
    const role = key.replace('_SK_B64', '');
    accounts[role] = {
      ...(accounts[role] ?? {}),
      secretKey: new Uint8Array(Buffer.from(value, 'base64')),
    };
  }
}

const client = new algosdk.Algodv2('', ALGOD_SERVER, ALGOD_PORT);

console.log('');
bar();
console.log('  ASSET OPT-IN');
console.log('  asset    : ' + assetId + '  (' + assetSymbol + ')');
console.log('  accounts : ' + Object.keys(accounts).length);
bar();
console.log('');
console.log('  Each opt-in costs ~0.001 ALGO in fees and raises the account');
console.log('  minimum balance by 0.1 ALGO. No asset balance is required.');
console.log('');

let succeeded = 0;
let skipped = 0;
let failed = 0;

for (const [role, account] of Object.entries(accounts)) {
  if (!account.address || !account.secretKey) {
    console.log('  ' + RED + 'SKIP    ' + RESET + role.padEnd(18) + 'missing address or key');
    failed += 1;
    continue;
  }

  // ---- already opted in? ----
  try {
    await client.accountAssetInformation(account.address, Number(assetId)).do();
    console.log('  ' + YELLOW + 'ALREADY ' + RESET + role.padEnd(18) + 'opted in, nothing to do');
    skipped += 1;
    continue;
  } catch {
    // 404 means not opted in. That is what we are here to fix.
  }

  // ---- opt in ----
  try {
    const params = await client.getTransactionParams().do();

    // An opt-in is an asset transfer of ZERO units from the account to itself.
    // algosdk v3 uses sender/receiver, not from/to.
    const txn = algosdk.makeAssetTransferTxnWithSuggestedParamsFromObject({
      sender: account.address,
      receiver: account.address,
      amount: 0,
      assetIndex: Number(assetId),
      suggestedParams: params,
    });

    const signed = txn.signTxn(account.secretKey);
    const response = await client.sendRawTransaction(signed).do();
    const txId = response.txid ?? response.txId;

    await algosdk.waitForConfirmation(client, txId, 8);

    console.log('  ' + GREEN + 'OPTED IN' + RESET + ' ' + role.padEnd(18) + txId);
    succeeded += 1;
  } catch (err) {
    const message = String(err.message).split('\n')[0];
    console.log('  ' + RED + 'FAILED  ' + RESET + role.padEnd(18) + message);
    console.log('           ' + DIM + account.address + RESET);
    failed += 1;
  }
}

console.log('');
bar();
console.log('  opted in : ' + succeeded);
console.log('  already  : ' + skipped);
console.log('  failed   : ' + failed);
console.log('');

if (failed === 0) {
  console.log('  ' + GREEN + 'ALL ACCOUNTS CAN NOW RECEIVE ' + assetSymbol + RESET);
  console.log('');
  console.log('  Next: the buyer still needs an actual balance.');
  console.log('  Try https://testnet.folks.finance/faucet with MSME_BUYER.');
} else {
  console.log('  ' + RED + 'SOME OPT-INS FAILED' + RESET + ' — see above.');
}
bar();
console.log('');

process.exitCode = failed === 0 ? 0 : 1;